language: csharp
solution: TauMulticastReferenceCSharp.sln

jobs:
  include:
    - dotnet: 2.1.502
      mono: none
      script:
        - dotnet restore TauMulticastReferenceCSharpCore.sln
        - dotnet build TauMulticastReferenceCSharpCore.sln
    - mono: latest